export * from './all-configs.interface'
export * from './grpc.interface'
export * from './database.interface'
export * from './redis.interface'
export * from './passport.interface'
export * from './telegram.interface'
